/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    books: Book;
    activities: Activity;
    articles: Article;
    loans: Loan;
    reviews: Review;
    'activity-registrations': ActivityRegistration;
    'book-favorites': BookFavorite;
    'article-favorites': ArticleFavorite;
    notifications: Notification;
    'waitlist-entries': WaitlistEntry;
    'loan-extensions': LoanExtension;
    logs: Log;
    'library-cards': LibraryCard;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    loans: LoansSelect<false> | LoansSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'activity-registrations': ActivityRegistrationsSelect<false> | ActivityRegistrationsSelect<true>;
    'book-favorites': BookFavoritesSelect<false> | BookFavoritesSelect<true>;
    'article-favorites': ArticleFavoritesSelect<false> | ArticleFavoritesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'waitlist-entries': WaitlistEntriesSelect<false> | WaitlistEntriesSelect<true>;
    'loan-extensions': LoanExtensionsSelect<false> | LoanExtensionsSelect<true>;
    logs: LogsSelect<false> | LogsSelect<true>;
    'library-cards': LibraryCardsSelect<false> | LibraryCardsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  faculty?: string | null;
  speciality?: string | null;
  studyYear?: ('1' | '2' | '3' | '4' | '5') | null;
  cardId?: string | null;
  situation?: ('student' | 'doctoral' | 'teacher' | 'staff') | null;
  sub?: string | null;
  role: 'admin' | 'librarian' | 'user';
  profilePicture?: (number | null) | Media;
  verificationDocument?: (number | null) | Media;
  verificationStatus?: ('pending_verification' | 'verified' | 'rejected') | null;
  verificationNote?: string | null;
  consentGiven?: boolean | null;
  consentTimestamp?: string | null;
  deletedAt?: string | null;
  deletionScheduledFor?: string | null;
  notificationPreferences?: {
    loanRequests?: boolean | null;
    activityRegistrations?: boolean | null;
    loanExtensions?: boolean | null;
    loanReturnReminder?: boolean | null;
    accountRequests?: boolean | null;
    overdueReturns?: boolean | null;
    newReviews?: boolean | null;
    activityLogEvents?: boolean | null;
  };
  activityLog?:
    | {
        action:
          | 'login'
          | 'password_changed'
          | 'profile_updated'
          | 'account_verified'
          | 'account_created'
          | 'first_admin_created';
        timestamp: string;
        metadata?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * وثائق التحقق من الهوية فقط. لا يمكن لغير المالك أو الإدارة الوصول إليها.
   */
  isPrivate?: boolean | null;
  owner?: (number | null) | User;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  deletedAt?: string | null;
  title: string;
  code?: string | null;
  loanDurationDays?: number | null;
  author: string;
  type: (
    | 'aqidah'
    | 'fiqh'
    | 'hadith'
    | 'tafsir'
    | 'sirah'
    | 'quranic-sciences'
    | 'dawah'
    | 'history'
    | 'philosophy'
    | 'mathematics'
    | 'physics'
    | 'chemistry'
    | 'biology'
    | 'engineering'
    | 'economics'
    | 'language'
    | 'other'
  )[];
  category?: ('religious' | 'scientific') | null;
  tags?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ratingCount?: number | null;
  averageRating?: number | null;
  publisher?: string | null;
  language?: ('fr' | 'ar' | 'en') | null;
  pageCount?: number | null;
  isbn?: string | null;
  editionNumber?: string | null;
  publishDate?: string | null;
  availableBooks?: number | null;
  totalBooks?: number | null;
  location?: string | null;
  image?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  type: 'aqidah' | 'fiqh' | 'hadith' | 'tafsir' | 'sirah' | 'language' | 'other';
  image: number | Media;
  shortDescription: string;
  longDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  benefits: {
    name?: string | null;
    id?: string | null;
  }[];
  targetAudience: {
    name?: string | null;
    id?: string | null;
  }[];
  location?: string | null;
  supervisor?: string | null;
  schedules?:
    | {
        dateAndTime: string;
        id?: string | null;
      }[]
    | null;
  openForRegistration?: boolean | null;
  registrationDeadline?: string | null;
  startDate: string;
  maxParticipants?: number | null;
  currentParticipants?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  publishDate?: string | null;
  type: 'aqidah' | 'fiqh' | 'hadith' | 'other';
  author: string;
  tags?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loans".
 */
export interface Loan {
  id: number;
  book: number | Book;
  user: number | User;
  status?: ('pending' | 'accepted' | 'picked_up' | 'returned' | 'refused') | null;
  loanDate: string;
  createdAt: string;
  dueDate?: string | null;
  pickupDate?: string | null;
  pickupHour?: string | null;
  pickupCode?: string | null;
  refusalReason?: string | null;
  returnDate?: string | null;
  overdueNotified?: boolean | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  user: number | User;
  book?: (number | null) | Book;
  article?: (number | null) | Article;
  rating: number;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-registrations".
 */
export interface ActivityRegistration {
  id: number;
  user: number | User;
  activity: number | Activity;
  attended?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-favorites".
 */
export interface BookFavorite {
  id: number;
  user: number | User;
  book: number | Book;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-favorites".
 */
export interface ArticleFavorite {
  id: number;
  user: number | User;
  article: number | Article;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  type?: ('loan' | 'waitlist' | 'extension' | 'verification' | 'request' | 'activity' | 'article' | 'system') | null;
  title: string;
  message: string;
  link?: string | null;
  seen?: boolean | null;
  emailSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-entries".
 */
export interface WaitlistEntry {
  id: number;
  book: number | Book;
  user: number | User;
  position: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loan-extensions".
 */
export interface LoanExtension {
  id: number;
  loan: number | Loan;
  user: number | User;
  status?: ('pending' | 'approved' | 'refused') | null;
  days: number;
  reason?: string | null;
  adminResponse?: string | null;
  originalDueDate?: string | null;
  newDueDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs".
 */
export interface Log {
  id: number;
  actor: number | User;
  action:
    | 'book_created'
    | 'book_updated'
    | 'book_deleted'
    | 'book_imported'
    | 'article_created'
    | 'article_updated'
    | 'article_deleted'
    | 'activity_created'
    | 'activity_updated'
    | 'activity_deleted'
    | 'review_deleted'
    | 'loan_approved'
    | 'loan_refused'
    | 'loan_picked_up'
    | 'loan_returned'
    | 'extension_approved'
    | 'extension_refused'
    | 'user_verified'
    | 'user_rejected'
    | 'user_role_changed'
    | 'user_deleted'
    | 'users_imported'
    | 'card_archived';
  targetType?: string | null;
  targetId?: string | null;
  timestamp: string;
  message: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "library-cards".
 */
export interface LibraryCard {
  id: number;
  cardId: string;
  user: number | User;
  status?: ('active' | 'archived') | null;
  issueDate: string;
  archivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'loans';
        value: number | Loan;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'activity-registrations';
        value: number | ActivityRegistration;
      } | null)
    | ({
        relationTo: 'book-favorites';
        value: number | BookFavorite;
      } | null)
    | ({
        relationTo: 'article-favorites';
        value: number | ArticleFavorite;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'waitlist-entries';
        value: number | WaitlistEntry;
      } | null)
    | ({
        relationTo: 'loan-extensions';
        value: number | LoanExtension;
      } | null)
    | ({
        relationTo: 'logs';
        value: number | Log;
      } | null)
    | ({
        relationTo: 'library-cards';
        value: number | LibraryCard;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  faculty?: T;
  speciality?: T;
  studyYear?: T;
  cardId?: T;
  situation?: T;
  sub?: T;
  role?: T;
  profilePicture?: T;
  verificationDocument?: T;
  verificationStatus?: T;
  verificationNote?: T;
  consentGiven?: T;
  consentTimestamp?: T;
  deletedAt?: T;
  deletionScheduledFor?: T;
  notificationPreferences?:
    | T
    | {
        loanRequests?: T;
        activityRegistrations?: T;
        loanExtensions?: T;
        loanReturnReminder?: T;
        accountRequests?: T;
        overdueReturns?: T;
        newReviews?: T;
        activityLogEvents?: T;
      };
  activityLog?:
    | T
    | {
        action?: T;
        timestamp?: T;
        metadata?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isPrivate?: T;
  owner?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  deletedAt?: T;
  title?: T;
  code?: T;
  loanDurationDays?: T;
  author?: T;
  type?: T;
  category?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  shortDescription?: T;
  longDescription?: T;
  ratingCount?: T;
  averageRating?: T;
  publisher?: T;
  language?: T;
  pageCount?: T;
  isbn?: T;
  editionNumber?: T;
  publishDate?: T;
  availableBooks?: T;
  totalBooks?: T;
  location?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  image?: T;
  shortDescription?: T;
  longDescription?: T;
  benefits?:
    | T
    | {
        name?: T;
        id?: T;
      };
  targetAudience?:
    | T
    | {
        name?: T;
        id?: T;
      };
  location?: T;
  supervisor?: T;
  schedules?:
    | T
    | {
        dateAndTime?: T;
        id?: T;
      };
  openForRegistration?: T;
  registrationDeadline?: T;
  startDate?: T;
  maxParticipants?: T;
  currentParticipants?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  publishDate?: T;
  type?: T;
  author?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  image?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loans_select".
 */
export interface LoansSelect<T extends boolean = true> {
  book?: T;
  user?: T;
  status?: T;
  loanDate?: T;
  createdAt?: T;
  dueDate?: T;
  pickupDate?: T;
  pickupHour?: T;
  pickupCode?: T;
  refusalReason?: T;
  returnDate?: T;
  overdueNotified?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  article?: T;
  rating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-registrations_select".
 */
export interface ActivityRegistrationsSelect<T extends boolean = true> {
  user?: T;
  activity?: T;
  attended?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-favorites_select".
 */
export interface BookFavoritesSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-favorites_select".
 */
export interface ArticleFavoritesSelect<T extends boolean = true> {
  user?: T;
  article?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  link?: T;
  seen?: T;
  emailSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist-entries_select".
 */
export interface WaitlistEntriesSelect<T extends boolean = true> {
  book?: T;
  user?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loan-extensions_select".
 */
export interface LoanExtensionsSelect<T extends boolean = true> {
  loan?: T;
  user?: T;
  status?: T;
  days?: T;
  reason?: T;
  adminResponse?: T;
  originalDueDate?: T;
  newDueDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs_select".
 */
export interface LogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  timestamp?: T;
  message?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "library-cards_select".
 */
export interface LibraryCardsSelect<T extends boolean = true> {
  cardId?: T;
  user?: T;
  status?: T;
  issueDate?: T;
  archivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  defaultLoanDurationDays?: number | null;
  borrowLimit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  defaultLoanDurationDays?: T;
  borrowLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}