import { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'

// No-op migration. The accompanying change (auth.forgotPassword email
// overrides in collections/User.ts) is configuration only and has no database
// footprint. The file exists to satisfy the migration guard, which requires
// any PR touching collections/ to ship a migration. The SQL generated by
// `payload migrate:create` for this change was exclusively drift from a
// local-only `payload_mcp_api_keys` table created by an MCP tool — that table
// does not belong to the app schema and must not be touched.
export async function up(_args: MigrateUpArgs): Promise<void> {}

export async function down(_args: MigrateDownArgs): Promise<void> {}
